import { Component, ChangeDetectionStrategy, output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-about',
  template: `
    <div class="fixed inset-0 bg-white/80 dark:bg-slate-900/90 backdrop-blur-sm z-40 animate-fade-in-fast"></div>
    <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div class="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl w-full max-w-3xl max-h-[90vh] shadow-2xl shadow-indigo-500/10 flex flex-col animate-fade-in-up">
        <header class="p-6 border-b border-slate-200 dark:border-slate-700 flex justify-between items-center flex-shrink-0">
          <h2 class="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-indigo-500 to-cyan-500 dark:from-indigo-400 dark:to-cyan-400">
            About Cosmic Clash
          </h2>
          <button (click)="close.emit()" class="text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors" aria-label="Close about page">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </header>
        
        <main class="p-6 sm:p-8 overflow-y-auto text-slate-600 dark:text-slate-300">
          <section class="mb-6">
            <h3 class="text-xl font-semibold text-cyan-600 dark:text-cyan-400 mb-2">What is Cosmic Clash?</h3>
            <p class="leading-relaxed">
              Cosmic Clash is an AI-powered battle simulator designed for fans of comics, anime, games, and fiction. It allows you to pit any two characters against each other and receive a detailed, hypothetical battle analysis. The simulation determines a winner based on a comprehensive evaluation of their powers, abilities, and established feats.
            </p>
          </section>

          <section class="mb-6">
            <h3 class="text-xl font-semibold text-cyan-600 dark:text-cyan-400 mb-2">How It Works</h3>
            <p class="leading-relaxed mb-2">
              The core of Cosmic Clash is powered by Google's advanced <span class="font-bold text-indigo-500 dark:text-indigo-400">Gemini 2.5 Flash</span> AI model. When you enter two challengers, the AI performs the following steps:
            </p>
            <ul class="list-disc list-inside text-slate-500 dark:text-slate-400 space-y-2 pl-4">
              <li>It accesses its vast knowledge base, drawing from fan wikis, official lore, and story arcs.</li>
              <li>It analyzes each character through the lens of powerscaling concepts to create a balanced comparison.</li>
              <li>It evaluates key attributes like strength, speed, durability, and unique abilities ("hax").</li>
              <li>Finally, it generates a detailed verdict, a summary, a statistical breakdown, and a conclusion explaining why the victor would likely win.</li>
            </ul>
          </section>

           <section class="mb-6">
            <h3 class="text-xl font-semibold text-cyan-600 dark:text-cyan-400 mb-2">What is Powerscaling?</h3>
            <p class="leading-relaxed">
              Powerscaling is a fan-driven practice of comparing the strengths and abilities of characters, often from different fictional universes. It involves analyzing character feats (their greatest demonstrated achievements) to establish a hierarchy of power. While it can be highly analytical, it remains a subjective and fun way for fans to engage with their favorite stories.
            </p>
          </section>

          <section>
            <h3 class="text-xl font-semibold text-cyan-600 dark:text-cyan-400 mb-2">Limitations</h3>
            <p class="leading-relaxed mb-2">
              While we strive for insightful and logical analysis, please remember:
            </p>
            <ul class="list-disc list-inside text-slate-500 dark:text-slate-400 space-y-2 pl-4">
              <li><span class="font-semibold text-slate-700 dark:text-slate-200">For Entertainment Only:</span> The results are generated by an AI and represent a fun, hypothetical outcome, not a definitive canonical fact.</li>
              <li><span class="font-semibold text-slate-700 dark:text-slate-200">AI Interpretation:</span> The AI's understanding is based on its training data, which may have gaps or reflect common fan interpretations that are not universally accepted.</li>
              <li><span class="font-semibold text-slate-700 dark:text-slate-200">Subjectivity:</span> Powerscaling is inherently subjective. Different interpretations of a character's abilities can lead to different conclusions.</li>
            </ul>
          </section>
        </main>

        <footer class="p-6 border-t border-slate-200 dark:border-slate-700 text-center flex-shrink-0">
           <button (click)="close.emit()" class="text-lg font-bold px-8 py-3 rounded-lg bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg shadow-indigo-600/30
               hover:from-indigo-700 hover:to-purple-700 transform hover:scale-105 transition-all duration-300 ease-in-out">
              Back to Battle
            </button>
        </footer>
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: contents;
    }
    .animate-fade-in-fast {
      animation: fadeIn 0.2s ease-in-out forwards;
    }
    .animate-fade-in-up {
      animation: fadeInUp 0.3s ease-in-out forwards;
    }
    @keyframes fadeIn {
      from { opacity: 0; }
      to { opacity: 1; }
    }
    @keyframes fadeInUp {
      from { opacity: 0; transform: translateY(20px) scale(0.98); }
      to { opacity: 1; transform: translateY(0) scale(1); }
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
})
export class AboutComponent {
  close = output<void>();
}